# Generated by Django 5.0.6 on 2026-06-19 12:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('products', '0002_firm_product_firm'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superuser', '系統管理員'), ('firm', '店家'), ('member', '會員')], default='member', max_length=20, verbose_name='角色'),
        ),
        migrations.CreateModel(
            name='MemberProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(default=1, verbose_name='會員等級')),
                ('points', models.PositiveIntegerField(default=0, verbose_name='累積點數')),
                ('total_spent', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='累積消費金額')),
                ('favorite_products', models.ManyToManyField(blank=True, related_name='favorited_by', to='products.product', verbose_name='喜好產品')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '會員資料',
                'verbose_name_plural': '會員資料',
            },
        ),
    ]
