# Generated by Django 5.0.6 on 2026-07-01 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('products', '0002_alter_brand_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='franchised_brands',
            field=models.ManyToManyField(blank=True, limit_choices_to={'brand_type': 'product_brand'}, related_name='franchise_masters', to='products.brand', verbose_name='加盟的產品品牌'),
        ),
        migrations.AddField(
            model_name='person',
            name='manager',
            field=models.ForeignKey(blank=True, limit_choices_to={'level': 'franchise_master'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_store_owners', to=settings.AUTH_USER_MODEL, verbose_name='所屬加盟主'),
        ),
        migrations.AlterField(
            model_name='person',
            name='level',
            field=models.CharField(choices=[('superuser', '系統管理員'), ('brand_owner', '品牌主'), ('franchise_master', '加盟主'), ('store_owner', '店主'), ('store_clerk', '店員'), ('member', '會員')], default='member', max_length=20, verbose_name='角色'),
        ),
    ]
