# Generated by Django 5.0.6 on 2026-06-19 12:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': '付款紀錄', 'verbose_name_plural': '付款紀錄'},
        ),
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='折扣金額'),
        ),
        migrations.AddField(
            model_name='order',
            name='fulfillment_type',
            field=models.CharField(choices=[('delivery', '宅配到府'), ('pickup', '到店取貨')], default='delivery', max_length=20, verbose_name='取貨方式'),
        ),
        migrations.AddField(
            model_name='order',
            name='guest_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='訪客姓名'),
        ),
        migrations.AddField(
            model_name='order',
            name='guest_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='訪客電話'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=models.CharField(blank=True, max_length=255, verbose_name='收件地址'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, help_text='訪客(guest)結帳時無對應會員帳號', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('credit_card', '信用卡'), ('line_pay', 'LINE Pay'), ('atm', 'ATM 轉帳'), ('store_cash', '到店付款')], max_length=20, verbose_name='付款方式'),
        ),
    ]
