# Generated by Django 5.0.6 on 2026-07-01 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='分類名稱')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='網址代稱')),
                ('sub_category_1', models.CharField(blank=True, max_length=50, verbose_name='子種類1')),
                ('sub_category_2', models.CharField(blank=True, max_length=50, verbose_name='子種類2')),
                ('sub_category_3', models.CharField(blank=True, max_length=50, verbose_name='子種類3')),
                ('sub_category_4', models.CharField(blank=True, max_length=50, verbose_name='子種類4')),
                ('sub_category_5', models.CharField(blank=True, max_length=50, verbose_name='子種類5')),
                ('description', models.TextField(blank=True, verbose_name='說明')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '產品種類',
                'verbose_name_plural': '產品種類',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_type', models.CharField(choices=[('product_brand', '產品品牌(連鎖總部)'), ('franchise_brand', '加盟品牌(門市)')], max_length=20, verbose_name='品牌類型')),
                ('name_en', models.CharField(blank=True, max_length=150, verbose_name='英文名')),
                ('name_zh', models.CharField(max_length=150, verbose_name='中文名')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='brands/', verbose_name='ICON')),
                ('website', models.URLField(blank=True, verbose_name='網址')),
                ('note', models.TextField(blank=True, help_text='純文字，用途後續再定義', verbose_name='備註')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('carried_product_brands', models.ManyToManyField(blank=True, help_text='僅加盟品牌使用，指向數筆「產品品牌(連鎖總部)」', related_name='carried_by_franchise_brands', to='products.brand', verbose_name='掛載的產品品牌')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_brands', to=settings.AUTH_USER_MODEL, verbose_name='聯絡人')),
                ('owner', models.ForeignKey(blank=True, help_text='僅加盟品牌使用，指向品牌主或店主', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_brands', to=settings.AUTH_USER_MODEL, verbose_name='門市負責人(品牌主/店主)')),
            ],
            options={
                'verbose_name': '品牌',
                'verbose_name_plural': '品牌',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='商品名稱')),
                ('slug', models.SlugField(blank=True, help_text='自動生成流水號', max_length=150, unique=True, verbose_name='網址代稱')),
                ('spec', models.CharField(blank=True, max_length=100, verbose_name='規格')),
                ('process', models.TextField(blank=True, verbose_name='製程')),
                ('suggested_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='建議價格')),
                ('selling_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='實售價格')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(help_text='種類名稱可能重複，實際選擇的是某一筆種類紀錄(以網址代稱區分)', on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.category', verbose_name='種類')),
                ('product_brand', models.ForeignKey(limit_choices_to={'brand_type': 'product_brand'}, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.brand', verbose_name='所屬產品品牌(連鎖總部)')),
            ],
            options={
                'verbose_name': '產品',
                'verbose_name_plural': '產品',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/', verbose_name='產品圖')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product', verbose_name='產品')),
            ],
            options={
                'verbose_name': '產品圖',
                'verbose_name_plural': '產品圖',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StoreProductListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='庫存')),
                ('is_active', models.BooleanField(default=True, verbose_name='上架中')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('franchise_brand', models.ForeignKey(limit_choices_to={'brand_type': 'franchise_brand'}, on_delete=django.db.models.deletion.CASCADE, related_name='store_listings', to='products.brand', verbose_name='門市(加盟品牌)')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_listings', to='products.product', verbose_name='產品')),
            ],
            options={
                'verbose_name': '門市商品上架',
                'verbose_name_plural': '門市商品上架',
                'unique_together': {('franchise_brand', 'product')},
            },
        ),
    ]
