# Generated by Django 5.0.6 on 2026-07-01 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='owner',
            field=models.OneToOneField(blank=True, help_text='產品品牌的唯一擁有者是品牌主，加盟品牌(門市)的唯一擁有者是店主', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_brand', to=settings.AUTH_USER_MODEL, verbose_name='唯一擁有者(品牌主/店主)'),
        ),
    ]
