# Generated by Django 5.0.6 on 2026-06-19 12:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Firm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='店家名稱')),
                ('description', models.TextField(blank=True, verbose_name='店家簡介')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='firm', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '店家',
                'verbose_name_plural': '店家',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='firm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.firm', verbose_name='所屬店家'),
        ),
    ]
