# Generated by Django 5.0.6 on 2026-07-01 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_brand_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeproductlisting',
            name='actual_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='門市實際售價，由店主或加盟主決定；未設定則採用產品的實售價格', max_digits=10, null=True, verbose_name='實際價格'),
        ),
    ]
