# Generated by Django 5.0.6 on 2026-06-19 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_firm_product_firm'),
    ]

    operations = [
        migrations.AddField(
            model_name='firm',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='地址'),
        ),
        migrations.AddField(
            model_name='firm',
            name='branch_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='分店名'),
        ),
        migrations.AddField(
            model_name='firm',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='電話'),
        ),
    ]
