# Generated by Django 5.0.6 on 2026-06-19 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_firm_address_firm_branch_name_firm_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='sub_category_1',
            field=models.CharField(blank=True, max_length=50, verbose_name='子種類1'),
        ),
        migrations.AddField(
            model_name='category',
            name='sub_category_2',
            field=models.CharField(blank=True, max_length=50, verbose_name='子種類2'),
        ),
        migrations.AddField(
            model_name='category',
            name='sub_category_3',
            field=models.CharField(blank=True, max_length=50, verbose_name='子種類3'),
        ),
        migrations.AddField(
            model_name='category',
            name='sub_category_4',
            field=models.CharField(blank=True, max_length=50, verbose_name='子種類4'),
        ),
        migrations.AddField(
            model_name='category',
            name='sub_category_5',
            field=models.CharField(blank=True, max_length=50, verbose_name='子種類5'),
        ),
        migrations.AddField(
            model_name='product',
            name='sub_category',
            field=models.CharField(blank=True, help_text='須為所屬種類底下已定義的子種類之一', max_length=50, verbose_name='子種類'),
        ),
    ]
