# Generated by Django 5.0.6 on 2026-07-07 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_storeproductlisting_actual_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Combo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='套餐名稱')),
                ('slug', models.SlugField(blank=True, help_text='自動生成流水號', max_length=150, unique=True, verbose_name='網址代稱')),
                ('suggested_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='建議價格')),
                ('selling_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='實售價格')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_brand', models.ForeignKey(limit_choices_to={'brand_type': 'product_brand'}, on_delete=django.db.models.deletion.PROTECT, related_name='combos', to='products.brand', verbose_name='所屬產品品牌(連鎖總部)')),
            ],
            options={
                'verbose_name': '套餐',
                'verbose_name_plural': '套餐',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComboItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='數量')),
                ('combo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='products.combo', verbose_name='套餐')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='combo_items', to='products.product', verbose_name='產品')),
            ],
            options={
                'verbose_name': '套餐內容',
                'verbose_name_plural': '套餐內容',
                'unique_together': {('combo', 'product')},
            },
        ),
        migrations.CreateModel(
            name='StoreComboListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='庫存')),
                ('actual_price', models.DecimalField(blank=True, decimal_places=2, help_text='門市實際售價，由店主或加盟主決定；未設定則採用套餐的實售價格', max_digits=10, null=True, verbose_name='實際價格')),
                ('is_active', models.BooleanField(default=True, verbose_name='上架中')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('combo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_listings', to='products.combo', verbose_name='套餐')),
                ('franchise_brand', models.ForeignKey(limit_choices_to={'brand_type': 'franchise_brand'}, on_delete=django.db.models.deletion.CASCADE, related_name='store_combo_listings', to='products.brand', verbose_name='門市(加盟品牌)')),
            ],
            options={
                'verbose_name': '門市套餐上架',
                'verbose_name_plural': '門市套餐上架',
                'unique_together': {('franchise_brand', 'combo')},
            },
        ),
    ]
