# Generated by Django 5.0.6 on 2026-07-07 04:35

from django.db import migrations


def backfill_product_brand(apps, schema_editor):
    """種類改為各品牌各自維護：依現有產品實際歸屬的產品品牌回填；
    沒有產品的種類則比照同名種類已回填的品牌"""
    Category = apps.get_model("products", "Category")
    Product = apps.get_model("products", "Product")

    by_name = {}
    for category in Category.objects.all():
        brand_ids = set(
            Product.objects.filter(category=category).values_list("product_brand_id", flat=True)
        )
        brand_ids.discard(None)
        if len(brand_ids) == 1:
            category.product_brand_id = brand_ids.pop()
            category.save(update_fields=["product_brand"])
            by_name.setdefault(category.name, category.product_brand_id)

    for category in Category.objects.filter(product_brand__isnull=True):
        brand_id = by_name.get(category.name)
        if brand_id:
            category.product_brand_id = brand_id
            category.save(update_fields=["product_brand"])


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_category_product_brand"),
    ]

    operations = [
        migrations.RunPython(backfill_product_brand, reverse_code=migrations.RunPython.noop),
    ]
