# Generated by Django 5.0.6 on 2026-06-19 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, help_text='自動生成流水號', max_length=150, unique=True, verbose_name='網址代稱'),
        ),
    ]
