# Generated by Django 5.0.6 on 2026-06-19 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sub_category',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(help_text='種類名稱可能重複，實際選擇的是某一筆種類紀錄(以網址代稱區分)', on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.category', verbose_name='種類'),
        ),
    ]
