# Generated by Django 5.0.6 on 2026-07-07 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_backfill_category_product_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='product_brand',
            field=models.ForeignKey(
                limit_choices_to={'brand_type': 'product_brand'},
                on_delete=django.db.models.deletion.PROTECT,
                related_name='categories',
                to='products.brand',
                verbose_name='所屬產品品牌(連鎖總部)',
            ),
        ),
    ]
