# Generated by Django 5.0.6 on 2026-06-19 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_product_sub_category_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='sku',
            field=models.CharField(blank=True, help_text='自動生成流水號', max_length=64, unique=True, verbose_name='商品編號'),
        ),
    ]
