# Generated by Django 5.0.6 on 2026-07-07 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_require_category_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='combo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='combos/', verbose_name='LOGO'),
        ),
    ]
