# Generated by Django 5.0.6 on 2026-06-19 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_productvariant_sku'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='品牌')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brands/', verbose_name='品牌LOGO')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('founder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='founded_brands', to=settings.AUTH_USER_MODEL, verbose_name='創始店主')),
                ('founding_firm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='founded_brands', to='products.firm', verbose_name='創始店面')),
            ],
            options={
                'verbose_name': '商店分類',
                'verbose_name_plural': '商店分類',
            },
        ),
    ]
