# Generated by Django 5.0.6 on 2026-06-19 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='firm',
        ),
        migrations.AddField(
            model_name='firm',
            name='brand',
            field=models.ForeignKey(blank=True, help_text='所賣的產品為同商店分類中的產品', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='firms', to='products.brand', verbose_name='商店分類'),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.brand', verbose_name='所屬店家分類'),
        ),
    ]
