# Generated by Django 5.0.6 on 2026-07-07 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('products', '0004_combo_comboitem_storecombolisting'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='combo_listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='products.storecombolisting'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='products.storeproductlisting'),
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'listing', 'combo_listing')},
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('combo_listing__isnull', True), ('listing__isnull', False)), models.Q(('combo_listing__isnull', False), ('listing__isnull', True)), _connector='OR'), name='cartitem_listing_xor_combo_listing'),
        ),
    ]
